In [2]:
symbols = "$*&!@"
codes = []

for symbol in symbols:
  codes.append(ord(symbol))

print(codes)

[36, 42, 38, 33, 64]


In [4]:
symbols = "$*&!@"
codes = [ord(symbol) for symbol in symbols]

print(codes)

[36, 42, 38, 33, 64]


In [6]:
x = '"!~$$*&!@'
dummy = [ord(x) for x in x]

print(x)
print(dummy)

"!~$$*&!@
[34, 33, 126, 36, 36, 42, 38, 33, 64]


In [8]:
symbols = '"!~$$*&@'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 32]

print(beyond_ascii)

[34, 33, 126, 36, 36, 42, 38, 64]


In [9]:
symbols = '"!~$$*&@'
beyond_ascii = list(filter(lambda c : c> 64, map(ord, symbols)))

print(beyond_ascii, '\n')

print(f"Map function:\n >>> {map(ord, symbols)}")
print(f"List after map:\n >>> {list(map(ord, symbols))}")

[126] 

Map function:
 >>> <map object at 0x7cab4a5c6470>
List after map:
 >>> [34, 33, 126, 36, 36, 42, 38, 64]


In [10]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]

print(tshirts)

for color in colors:
  for size in sizes:
    print((color, size))

[('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]
('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [11]:
symbols = "!#^&&#"
ord_s = tuple(ord(s) for s in symbols if ord(s))

print(ord_s)

(33, 35, 94, 38, 38, 35)


In [12]:
import array

ord_s = array.array('I', (ord(symbol) for symbol in symbols))

print(ord_s)

array('I', [33, 35, 94, 38, 38, 35])


In [13]:
colors = ['black','white']
sizes = ['S','M', 'L']

for tshirt in ('{} {}'.format(c,s) for s in sizes for c in colors):
  print(tshirt)

black S
white S
black M
white M
black L
white L


In [15]:
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area =('Tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '32295855'),
                ('BRA', 'CE343567'),
                ('ESP', 'XDA205856')]

for passport in sorted(traveler_ids):
  print('%s/%s' % passport)
  print('{}/{}'.format(passport[0], passport[1]))
  print(f'{passport[0]}/{passport[1]}')

BRA/CE343567
BRA/CE343567
BRA/CE343567
ESP/XDA205856
ESP/XDA205856
ESP/XDA205856
USA/32295855
USA/32295855
USA/32295855


In [16]:
for country, _ in traveler_ids:
  print(country)

USA
BRA
ESP


In [17]:
lax_coordinates = (33.9425, -118.408056)
latitude, longtitude = lax_coordinates
print(latitude)
print(longtitude)

33.9425
-118.408056


In [18]:
a = 10; b = 20
b, a = a, b
print(a, b)

20 10


In [19]:
divmod(20, 8)

(2, 4)

In [20]:
t = (20, 8)
divmod(*t)

(2, 4)

In [21]:
quotient, remainder = divmod(*t)
quotient, remainder

(2, 4)

In [22]:
import os
_, filename = os.path.split('/home/luciano/.ssh/idrsa.pub')
filename

'idrsa.pub'

In [23]:
a, b, *rest = range(5)
a, b, rest

(0, 1, [2, 3, 4])

In [24]:
a, b, *rest = range(3)
a, b, rest

(0, 1, [2])

In [25]:
a, b, *rest = range(2)
a, b, rest

(0, 1, [])

In [26]:
a, *body, c, d = range(5)
a, body, c, d

(0, [1, 2], 3, 4)

In [27]:
*head, b, c, d = range(5)
head, b, c, d

([0, 1], 2, 3, 4)

In [29]:
metro_areas = [
    ("Tolyo", "JP", 36.933, (35, 139)),
    ("Delhi NCR", "IN", 21, (28, 77)),
    ("Mexico City", "MX", 20, (19, -99)),
    ("New York-Newark", "US", 20, (40, -74)),
    ("Sao Paulo", "BR", 19, (-23, -46))
]

print("{:15} | {:^9} | {:^9}".format('', 'lat.', 'long.'))
fmt = '{:15} | {:9.4f} | {:9.4f}'
for name, cc, pop, (latitude, longtitude) in metro_areas:
  if longtitude <= 0:
    print(fmt.format(name, latitude, longtitude))

                |   lat.    |   long.  
Mexico City     |   19.0000 |  -99.0000
New York-Newark |   40.0000 |  -74.0000
Sao Paulo       |  -23.0000 |  -46.0000


In [ ]:
from collections import namedtuple

City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35, 139))
tokyo

In [31]:
tokyo.population

36.933

In [32]:
tokyo.coordinates

(35, 139)

In [33]:
tokyo[1]

'JP'

In [35]:
City._fields

('name', 'country', 'population', 'coordinates')

In [37]:
LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.631, 77.208))
delhi = City._make(delhi_data)
delhi._asdict()

{'name': 'Delhi NCR',
 'country': 'IN',
 'population': 21.935,
 'coordinates': LatLong(lat=28.631, long=77.208)}

In [38]:
for key, value in delhi._asdict().items():
  print(key + ':', value)

name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.631, long=77.208)


In [39]:
l = [10, 20, 30, 40, 50, 60]
l[:2]

[10, 20]

In [40]:
l[2:]

[30, 40, 50, 60]

In [41]:
l[:3]

[10, 20, 30]

In [42]:
l[3:]

[40, 50, 60]

In [ ]:
invoice = """
0.....6......................25...........33.........40........
1909  Pimoroni              $17.50  3  $52.50
1489  6mm Tactile           $4.95   2  $9.90
"""

SKU = slice(0,6)
DESCRIPTION = slice(6, 25)
UNIT_PRICE = slice(25, 33)
QUANTITY = slice(33, 40)
ITEM_TOTAL = slice(40, None)
line_items = invoice.split('\n')[2:]

for item in line_items:
  print(item[UNIT_PRICE], item[DESCRIPTION])

In [51]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [52]:
l[2:5]  = [20, 30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [53]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [54]:
l[3::2] = [11, 22]
l

[0, 1, 20, 11, 5, 22, 9]

In [55]:
l[2:5] = [100]
l

[0, 1, 100, 22, 9]

In [56]:
l = [1, 2, 3]
l * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [57]:
5 * 'abcd'

'abcdabcdabcdabcdabcd'

In [59]:
board = [['_'] * 3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [60]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [61]:
weird_board = [['_'] * 3] * 3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [63]:
weird_board[1][2] = '0'
weird_board

[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]

In [64]:
row = ['_'] * 3
board = []
for i in range(3):
  board.append(row)
board[1][2] = 'X'
board

[['_', '_', 'X'], ['_', '_', 'X'], ['_', '_', 'X']]

In [66]:
board = []
for i in range(3):
  row = ['_'] * 3
  board.append(row)
print(board)
board[2][0] = 'X'
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]


[['_', '_', '_'], ['_', '_', '_'], ['X', '_', '_']]

In [67]:
l = [1,2,3]
id(l)

137075127602304

In [68]:
l *= 2
l

[1, 2, 3, 1, 2, 3]

In [69]:
id(l)

137075127602304

In [70]:
t = (1, 2, 3)
id(t)

137075127162752

In [71]:
t *= 2
id(t)

137075129079872

In [72]:
t = (1, 2, [30, 40])
print(t)
t[2] += [50, 60]

(1, 2, [30, 40])


TypeError: 'tuple' object does not support item assignment

In [73]:
print(t)

(1, 2, [30, 40, 50, 60])


In [74]:
fruits = ['grape', 'raspberry', 'apple', 'banana']
print(fruits)

['grape', 'raspberry', 'apple', 'banana']


In [75]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [76]:
sorted(fruits, reverse = True)

['raspberry', 'grape', 'banana', 'apple']

In [77]:
sorted(fruits, key = len)

['grape', 'apple', 'banana', 'raspberry']

In [78]:
sorted(fruits, key = len, reverse = True)

['raspberry', 'banana', 'grape', 'apple']

In [79]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [80]:
fruits.sort()
fruits

['apple', 'banana', 'grape', 'raspberry']

In [81]:
from array import array
from random import random

floats = array('d', (random() for i in range(10**7)))
floats[-1]

0.5712756050820849

In [82]:
import array
numbers = array.array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
len(memv)

5

In [83]:
memv[0]

-2

In [84]:
memv_oct = memv.cast('B')
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [85]:
memv_oct[5] = 4
numbers

array('h', [-2, -1, 1024, 1, 2])

In [87]:
import numpy
a = numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [88]:
type(a)

numpy.ndarray

In [89]:
a.shape

(12,)

In [90]:
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
a[2]

array([ 8,  9, 10, 11])

In [92]:
a[2,1]

9

In [93]:
a[:, 1]

array([1, 5, 9])

In [94]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [95]:
from collections import deque
dq = deque(range(10), maxlen = 10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
dq.rotate(3)
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [97]:
dq.rotate(-4)
dq

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [98]:
dq.appendleft(-1)
dq

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
dq.extend([11, 22, 33])
dq

deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33])

In [100]:
dq.extendleft([10, 20, 30, 40])
dq

deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8])